### ISSUE TITLE
Incorrect Linkedin url in play store.

### ISSUE THREAD

**Issue by yalexx** [zyra/cordova-plugin-linkedin#17]
I get Notification: This app is no longer available for purchase or is not supported in this country or on this device.
(com.linkedin.android:2290:4002) 

When I don't have the native app, instead of redirecting me to the Play Store to download LinkedIn

**Comment by ihadeed** [comment]
If you go to the app store manually to download the linked in app, are you able to install it?

**Comment by PaolinoD** [comment]
@yalexx I had the same error on a Samsung device. After some hours spent in debugging, I understood that it was an SDK 'failure' and not a plugin fault.

In my case the Store reporting that error was the Samsung ones installed on the device. To workaround that issue I've used another plugin already in use in my application. In other words I call the 'login' function only if the LinkedIn app is already installed on the device, otherwise I'am the one that takes in charge of the Store opening.

Hope this helps.

--p

**Comment by ihadeed** [comment]
Thanks for the information @PailinoD 

I'll try to find a way to contact LinkedIn and let them know about this issue.

**Comment by yalexx** [comment]
Hello Paolino how do you check if the LinkedIn app is already installed? Can you share the name of the plugin you are using?

**Comment by ihadeed** [comment]
@yalexx the plugin is called "App Availability". You can google it, or find it in Ionic Native (if you're using Ionic).
