### ISSUE TITLE
FYI IOS fails release

### ISSUE THREAD

**Issue by Ross-Rawlins** [zyra/cordova-plugin-linkedin#21]
Itunes rejected my app because I prompted the user to install the linked in when they tried to login with linked in. I am setting the prompt to install to false to pass this and just passing on the information.

**Comment by Sampath-Lokuge** [comment]
@Ross-Rawlins Thanks for the info :)

**Comment by ihadeed** [comment]
I'll leave a note in the docs to let people know. This is not something I can fix on my end since it's a feature of the SDK.

What I suggest you do in this situation is: use the app availability plugin (found on Ionic Native as well) to check if the LinkedIn App is installed before attempting to login. Then you can display a more friendly message saying that logging in with LinkedIn is only available if the app is installed (a Toast can work). Apple should be fine with this type of info/error message, since it doesn't directly ask the user to install another app..

**Comment by Sampath-Lokuge** [comment]
@ihadeed Yes, Please update the doc and your suggestion is awesome too.Thanks.

**Comment by Ross-Rawlins** [comment]
I did do that exact solution for the problem.

**Comment by acipher** [comment]
Did you gone through on store? Issue https://github.com/zyra/cordova-plugin-linkedin/issues/55

**Comment by tobiasmuecksch** [comment]
What is the app id of LinkedIn for availability check?
