### ISSUE TITLE
Know if LinkedIn app is installed or redirect user on Store - Nice to have?

### ISSUE THREAD

**Issue by PaolinoD** [zyra/cordova-plugin-linkedin#32]
Hi @ihadeed ,

reading the issue list, it seems that functions to check LinkedIn app availability and / or redirecting users on Store could be very useful - especially for Android users (https://github.com/zyra/cordova-plugin-linkedin/issues/17).

I've already implemented the first one on [my fork](https://github.com/PaolinoD/cordova-plugin-linkedin/tree/features/20170731_isInstalled). If you think those functions may be useful, let me know, and I'll make a PR.

--p

**Comment by lucasbasquerotto** [comment]
@PaolinoD Thanks, your solution worked (tested with Android only). I just changed the Android code to return `false` if the App is not installed, instead of throwing an error (it throws an error if some unexpected error occurs in the process):

```
private void isLinkedInAppInstalled(CallbackContext callbackContext) {
	try {
		PackageManager pm = cordova.getActivity().getApplicationContext().getPackageManager();
		pm.getPackageInfo(LINKEDIN_PACKAGE_ID, PackageManager.GET_ACTIVITIES);
		
		callbackContext.sendPluginResult(new PluginResult(PluginResult.Status.OK, true));
	} catch (NameNotFoundException e) {
		callbackContext.sendPluginResult(new PluginResult(PluginResult.Status.OK, false));
	} catch (Exception e) {
		callbackContext.error(e.getMessage());
	}
}
```

I made [this fork](https://github.com/lucasbasquerotto/cordova-plugin-linkedin) with the changes, and also to support `cordova-android@7+`, because it seems this repo is not regularly updated (the last commit was around than 6 months ago).
