### ISSUE TITLE
Linked in Login does not fire any callback on IOS

### ISSUE THREAD

**Issue by crajbanshi** [zyra/cordova-plugin-linkedin#45]
I am using cordova-plugin-linkedin@1.2.1

On Android device, it is working fine, but IOS does not do anything, not fire success or fail callback for both formats.

`var scopes = ['r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share'];`

1st :  `cordova.plugins.LinkedIn.login(scopes, true, onSuccess, onError)`
- on Android, its working, Do nothing for IOS

2nd:  `cordova.plugins.LinkedIn.login(scopes, true, onSuccess, onError)`

- On Android, 
Error: Uncaught (in promise) TypeError: Cannot read property 'then' of undefined

- On IOS,

Error in Success callbackId: LinkedIn77629818 : TypeError: undefined is not an object (evaluating 'cordova.plugins.LinkedIn.login(scopes, true).then')

Hardly finding the solution for IOS.

Someone Please help me to solve this problem.

**Comment by gertgjoka** [comment]
For me the problem was having another plugin (cordova-plugin-ms-azure-mobile-apps ) which had an AppDelegate (AppDelegate+MobileServicesPlugin.m) with openURL function, and that was overriding the linkedin openURL, so basically when flow returns from LinkedIn app to your app, that would be intercepted by the other AppDelegate which doesnt handle our url schema (liAPPID). Removing that fixed the issue for me. Check for other AppDelegates on your plugins
